### PR TITLE
Add Easer, an automation app

### PR DESCRIPTION
**Pull request by daraul**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Awesome! We decided to host the project to [Codeberg](https://codeberg.org/LinuxCafeFederation/awesome-android), and we are struggling to mirror it to GitHub. I'll keep it opened, but we'll try to mirror it as soon as possible so we can merge

**Comment by TheEvilSkeleton** [comment]
Hope this works

**Comment by TheEvilSkeleton** [comment]
SEEMS LIKE IT WORKED https://codeberg.org/LinuxCafeFederation/awesome-android/commit/f48ce39d9e94d089ce91a09b5478cdcc29aaa86b. Thank you so much for the contribution

**Comment by daraul** [comment]
Lol happy to help!

**Pull request merged**
