### PR TITLE
- Added few Jetpack Compose Libraries

### PR DESCRIPTION
**Pull request by yashwantGowla**

### CODE REVIEW

**Comment by yashwantGowla** [comment]
@CipherOps kindly look into it.

**Comment by yashwantGowla** [comment]
@CipherOps Kindly look into it.

**Comment by yashwantGowla** [comment]
@CipherOps Kindly look into it.

**Review by LeoColman — CHANGES_REQUESTED** [review]
These are libraries. The repository collects apps.

**Comment by CipherOps** [comment]
Since the last update I've got a full-time job and life stuff so not as much time to devote to this anymore.

This is just a mirror, the project is maintained at https://gitlab.com/linuxcafefederation/awesome-android

You can submit a PR there and I'll accept it.

**Pull request closed without merging**
